version: '1.0'

services:

### Container used for downloading data
  dwnld_data_py:
    build: 
      context: dwnld_data
      args: 
        - SYSTEM_USER_NAME=root
        - WORK_DIR=/root
        - DTTM=$(date +%s)
    volumes:
      - dwld_data_sql_vol:/root/data

### MySQL container
  mysql_epo:
    build:
      context: mysql
      args:
        - SYSTEM_USER_NAME=root
        - WORK_DIR=/root
        - MYSQL_ROOT_PASSWORD=123
    ports:
      - "3307:3306"
    volumes:
      - dwld_data_sql_vol:/var/lib/mysql-files

volumes:
  dwld_data_sql_vol:
    external: false
    driver: local
    driver_opts:
      type: none
      device: ./volume_mount
      o: bind 